"""i7 forecasting tables

Revision ID: 0a91caeb3d2a
Revises: d53fcb8300da
Create Date: 2026-09-11 14:57:26.528009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a91caeb3d2a'
down_revision: Union[str, Sequence[str], None] = 'd53fcb8300da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i7_forecast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_run_id', sa.Integer(), nullable=False),
    sa.Column('sap_material_number', sa.String(length=40), nullable=False),
    sa.Column('sap_plant_code', sa.String(length=8), nullable=False),
    sa.Column('demand_class', sa.String(length=32), nullable=False),
    sa.Column('history_status', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('forecast_status', sa.String(length=64), nullable=False),
    sa.Column('forecast_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('forecast_unit', sa.String(length=8), nullable=True),
    sa.Column('training_start', sa.Date(), nullable=True),
    sa.Column('training_end', sa.Date(), nullable=True),
    sa.Column('horizon_months', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.String(length=500), nullable=True),
    sa.Column('backtest_status', sa.String(length=64), nullable=False),
    sa.Column('required_origins', sa.Integer(), nullable=False),
    sa.Column('available_origins', sa.Integer(), nullable=False),
    sa.Column('origins_evaluated', sa.Integer(), nullable=False),
    sa.Column('pinball_loss', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('pinball_status', sa.String(length=32), nullable=True),
    sa.Column('mean_error', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('bias_percentage', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('mean_absolute_error', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('fill_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('fill_rate_status', sa.String(length=32), nullable=True),
    sa.Column('holding_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('holding_cost_status', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_forecast')),
    sa.UniqueConstraint('forecast_run_id', 'sap_material_number', 'sap_plant_code', 'model_name', name='uq_i7_forecast_key')
    )
    op.create_index(op.f('ix_i7_forecast_backtest_status'), 'i7_forecast', ['backtest_status'], unique=False)
    op.create_index('ix_i7_forecast_class_model', 'i7_forecast', ['demand_class', 'model_name'], unique=False)
    op.create_index(op.f('ix_i7_forecast_forecast_run_id'), 'i7_forecast', ['forecast_run_id'], unique=False)
    op.create_index(op.f('ix_i7_forecast_forecast_status'), 'i7_forecast', ['forecast_status'], unique=False)
    op.create_index('ix_i7_forecast_material_plant', 'i7_forecast', ['sap_material_number', 'sap_plant_code'], unique=False)
    op.create_table('i7_forecast_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('feature_run_id', sa.Integer(), nullable=True),
    sa.Column('target_quantile', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('forecasts_written', sa.Integer(), nullable=False),
    sa.Column('materials_evaluated', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_forecast_run'))
    )
    op.create_index(op.f('ix_i7_forecast_run_status'), 'i7_forecast_run', ['status'], unique=False)
    op.create_table('i7_segment_decision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_run_id', sa.Integer(), nullable=False),
    sa.Column('segment_key', sa.String(length=64), nullable=False),
    sa.Column('baseline_model', sa.String(length=32), nullable=False),
    sa.Column('challenger_model', sa.String(length=32), nullable=True),
    sa.Column('baseline_pinball', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('challenger_pinball', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('improvement', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('baseline_bias', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('challenger_bias', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('bias_change', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('origins_available', sa.Integer(), nullable=False),
    sa.Column('origins_evaluated', sa.Integer(), nullable=False),
    sa.Column('required_origins', sa.Integer(), nullable=False),
    sa.Column('adoption_status', sa.String(length=64), nullable=False),
    sa.Column('decision_reason', sa.String(length=500), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_segment_decision')),
    sa.UniqueConstraint('forecast_run_id', 'segment_key', name='uq_i7_segment_decision_key')
    )
    op.create_index(op.f('ix_i7_segment_decision_adoption_status'), 'i7_segment_decision', ['adoption_status'], unique=False)
    op.create_index(op.f('ix_i7_segment_decision_forecast_run_id'), 'i7_segment_decision', ['forecast_run_id'], unique=False)
    op.create_index(op.f('ix_i7_segment_decision_segment_key'), 'i7_segment_decision', ['segment_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_i7_segment_decision_segment_key'), table_name='i7_segment_decision')
    op.drop_index(op.f('ix_i7_segment_decision_forecast_run_id'), table_name='i7_segment_decision')
    op.drop_index(op.f('ix_i7_segment_decision_adoption_status'), table_name='i7_segment_decision')
    op.drop_table('i7_segment_decision')
    op.drop_index(op.f('ix_i7_forecast_run_status'), table_name='i7_forecast_run')
    op.drop_table('i7_forecast_run')
    op.drop_index('ix_i7_forecast_material_plant', table_name='i7_forecast')
    op.drop_index(op.f('ix_i7_forecast_forecast_status'), table_name='i7_forecast')
    op.drop_index(op.f('ix_i7_forecast_forecast_run_id'), table_name='i7_forecast')
    op.drop_index('ix_i7_forecast_class_model', table_name='i7_forecast')
    op.drop_index(op.f('ix_i7_forecast_backtest_status'), table_name='i7_forecast')
    op.drop_table('i7_forecast')
    # ### end Alembic commands ###
