"""forecast backtest path table

Revision ID: 0bffdfda3487
Revises: b1c7daec9aca
Create Date: 2026-09-22 16:55:11.400826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bffdfda3487'
down_revision: Union[str, Sequence[str], None] = 'b1c7daec9aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i7_forecast_backtest_path',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_run_id', sa.Integer(), nullable=False),
    sa.Column('sap_material_number', sa.String(length=40), nullable=False),
    sa.Column('sap_plant_code', sa.String(length=8), nullable=False),
    sa.Column('model_name', sa.String(length=32), nullable=False),
    sa.Column('origin_period', sa.Date(), nullable=False),
    sa.Column('horizon_step', sa.Integer(), nullable=False),
    sa.Column('forecast_period', sa.Date(), nullable=False),
    sa.Column('predicted', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('actual', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_forecast_backtest_path'))
    )
    op.create_index(op.f('ix_i7_forecast_backtest_path_forecast_run_id'), 'i7_forecast_backtest_path', ['forecast_run_id'], unique=False)
    op.create_index('ix_i7_forecast_backtest_path_material_plant', 'i7_forecast_backtest_path', ['sap_material_number', 'sap_plant_code'], unique=False)
    op.create_index('ix_i7_forecast_backtest_path_run', 'i7_forecast_backtest_path', ['forecast_run_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected a pre-existing, unrelated index drift
    # on ix_i7_oar_target_status (single- vs two-column, flip-flopped across
    # Phases 6/7 -- see docs/i07_sit.md's "Known limitations"). Deliberately
    # excluded from this migration: this migration is scoped to the new
    # i7_forecast_backtest_path table only, per the project rule against
    # unrelated changes riding along in one migration.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_i7_forecast_backtest_path_run', table_name='i7_forecast_backtest_path')
    op.drop_index('ix_i7_forecast_backtest_path_material_plant', table_name='i7_forecast_backtest_path')
    op.drop_index(op.f('ix_i7_forecast_backtest_path_forecast_run_id'), table_name='i7_forecast_backtest_path')
    op.drop_table('i7_forecast_backtest_path')
    # ### end Alembic commands ###
