"""add unit price to i7_material_feature

Revision ID: 1059fe4c7ddd
Revises: f7684f17af15
Create Date: 2026-09-16 15:38:55.468445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1059fe4c7ddd'
down_revision: Union[str, Sequence[str], None] = 'f7684f17af15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('i7_material_feature', sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('i7_material_feature', sa.Column('currency', sa.String(length=8), nullable=True))
    op.add_column(
        'i7_material_feature',
        sa.Column('has_unit_price', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # Note: autogenerate also detected an ix_i7_oar_target_status index drift
    # (a pre-existing, unrelated mismatch between the OAR model and this local
    # database). Deliberately not included here -- this migration is scoped to
    # unit_price only.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('i7_material_feature', 'has_unit_price')
    op.drop_column('i7_material_feature', 'currency')
    op.drop_column('i7_material_feature', 'unit_price')
    # ### end Alembic commands ###
