"""i7 inventory calculations

Revision ID: 14dfbb4d28ec
Revises: 0a91caeb3d2a
Create Date: 2026-09-11 15:26:20.004577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14dfbb4d28ec'
down_revision: Union[str, Sequence[str], None] = '0a91caeb3d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i7_inventory_calculation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventory_run_id', sa.Integer(), nullable=False),
    sa.Column('sap_material_number', sa.String(length=40), nullable=False),
    sa.Column('sap_plant_code', sa.String(length=8), nullable=False),
    sa.Column('demand_class', sa.String(length=32), nullable=False),
    sa.Column('selected_model', sa.String(length=32), nullable=True),
    sa.Column('forecast_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('forecast_unit', sa.String(length=8), nullable=True),
    sa.Column('lead_time_status', sa.String(length=48), nullable=False),
    sa.Column('lead_time_method', sa.String(length=32), nullable=True),
    sa.Column('po_count', sa.Integer(), nullable=False),
    sa.Column('valid_po_count', sa.Integer(), nullable=False),
    sa.Column('excluded_cancelled_count', sa.Integer(), nullable=False),
    sa.Column('excluded_lt_error_count', sa.Integer(), nullable=False),
    sa.Column('outlier_count', sa.Integer(), nullable=False),
    sa.Column('lt_avg_days', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('lt_avg_months', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sigma_lt_days', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sigma_lt_months', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('planned_lt_days', sa.Integer(), nullable=True),
    sa.Column('variability_status', sa.String(length=48), nullable=False),
    sa.Column('n_periods', sa.Integer(), nullable=False),
    sa.Column('zero_period_count', sa.Integer(), nullable=False),
    sa.Column('d_avg', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sigma_d', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('service_level_status', sa.String(length=48), nullable=False),
    sa.Column('service_level', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('z_factor', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('criticality', sa.String(length=16), nullable=True),
    sa.Column('circuit', sa.String(length=32), nullable=True),
    sa.Column('safety_stock_status', sa.String(length=48), nullable=False),
    sa.Column('safety_stock_method', sa.String(length=32), nullable=True),
    sa.Column('raw_safety_stock', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('safety_stock', sa.Integer(), nullable=True),
    sa.Column('safety_stock_trace', sa.String(length=1000), nullable=True),
    sa.Column('rop_status', sa.String(length=48), nullable=False),
    sa.Column('expected_lead_time_demand', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('raw_rop', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('rop', sa.Integer(), nullable=True),
    sa.Column('rop_trace', sa.String(length=1000), nullable=True),
    sa.Column('max_stock_status', sa.String(length=48), nullable=False),
    sa.Column('max_stock_strategy', sa.String(length=32), nullable=True),
    sa.Column('raw_max_stock', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('max_stock', sa.Integer(), nullable=True),
    sa.Column('max_stock_trace', sa.String(length=1000), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_inventory_calculation')),
    sa.UniqueConstraint('inventory_run_id', 'sap_material_number', 'sap_plant_code', name='uq_i7_inventory_calculation_key')
    )
    op.create_index(op.f('ix_i7_inventory_calculation_inventory_run_id'), 'i7_inventory_calculation', ['inventory_run_id'], unique=False)
    op.create_index(op.f('ix_i7_inventory_calculation_lead_time_status'), 'i7_inventory_calculation', ['lead_time_status'], unique=False)
    op.create_index('ix_i7_inventory_calculation_material_plant', 'i7_inventory_calculation', ['sap_material_number', 'sap_plant_code'], unique=False)
    op.create_index(op.f('ix_i7_inventory_calculation_max_stock_status'), 'i7_inventory_calculation', ['max_stock_status'], unique=False)
    op.create_index(op.f('ix_i7_inventory_calculation_rop_status'), 'i7_inventory_calculation', ['rop_status'], unique=False)
    op.create_index(op.f('ix_i7_inventory_calculation_safety_stock_status'), 'i7_inventory_calculation', ['safety_stock_status'], unique=False)
    op.create_index(op.f('ix_i7_inventory_calculation_service_level_status'), 'i7_inventory_calculation', ['service_level_status'], unique=False)
    op.create_index('ix_i7_inventory_calculation_status', 'i7_inventory_calculation', ['safety_stock_status', 'demand_class'], unique=False)
    op.create_table('i7_inventory_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('feature_run_id', sa.Integer(), nullable=True),
    sa.Column('forecast_run_id', sa.Integer(), nullable=True),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('formula_version', sa.String(length=64), nullable=False),
    sa.Column('service_level_configured', sa.Boolean(), nullable=False),
    sa.Column('max_stock_strategy', sa.String(length=32), nullable=True),
    sa.Column('calculations_written', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_inventory_run')),
    sa.UniqueConstraint('feature_run_id', 'forecast_run_id', 'policy_id', 'policy_version', 'formula_version', name='uq_i7_inventory_run_inputs')
    )
    op.create_index(op.f('ix_i7_inventory_run_status'), 'i7_inventory_run', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_i7_inventory_run_status'), table_name='i7_inventory_run')
    op.drop_table('i7_inventory_run')
    op.drop_index('ix_i7_inventory_calculation_status', table_name='i7_inventory_calculation')
    op.drop_index(op.f('ix_i7_inventory_calculation_service_level_status'), table_name='i7_inventory_calculation')
    op.drop_index(op.f('ix_i7_inventory_calculation_safety_stock_status'), table_name='i7_inventory_calculation')
    op.drop_index(op.f('ix_i7_inventory_calculation_rop_status'), table_name='i7_inventory_calculation')
    op.drop_index(op.f('ix_i7_inventory_calculation_max_stock_status'), table_name='i7_inventory_calculation')
    op.drop_index('ix_i7_inventory_calculation_material_plant', table_name='i7_inventory_calculation')
    op.drop_index(op.f('ix_i7_inventory_calculation_lead_time_status'), table_name='i7_inventory_calculation')
    op.drop_index(op.f('ix_i7_inventory_calculation_inventory_run_id'), table_name='i7_inventory_calculation')
    op.drop_table('i7_inventory_calculation')
    # ### end Alembic commands ###
