"""oar similarity status columns

Revision ID: 64f7682e1dc1
Revises: 9392a322f0a5
Create Date: 2026-09-12 10:46:50.603331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f7682e1dc1'
down_revision: Union[str, Sequence[str], None] = '9392a322f0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_i7_oar_target_status'), table_name='i7_oar_target')
    op.create_index(op.f('ix_i7_oar_target_status'), 'i7_oar_target', ['status'], unique=False)
    op.add_column('i7_recommendation', sa.Column('oar_similarity_status', sa.String(length=16), nullable=True))
    op.add_column('i7_recommendation', sa.Column('oar_estimate_status', sa.String(length=48), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('i7_recommendation', 'oar_estimate_status')
    op.drop_column('i7_recommendation', 'oar_similarity_status')
    op.drop_index(op.f('ix_i7_oar_target_status'), table_name='i7_oar_target')
    op.create_index(op.f('ix_i7_oar_target_status'), 'i7_oar_target', ['status', 'confidence'], unique=False)
    # ### end Alembic commands ###
