"""i7 policy version

Revision ID: 6ed5f8189d4a
Revises: 770e63ee2f68
Create Date: 2026-09-11 12:45:46.753489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed5f8189d4a'
down_revision: Union[str, Sequence[str], None] = '770e63ee2f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i7_policy_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('document_json', sa.Text(), nullable=False),
    sa.Column('signed_by', sa.String(length=128), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_policy_version')),
    sa.UniqueConstraint('policy_id', 'policy_version', name='uq_i7_policy_version_id_version')
    )
    op.create_index(op.f('ix_i7_policy_version_policy_id'), 'i7_policy_version', ['policy_id'], unique=False)
    op.create_index(op.f('ix_i7_policy_version_status'), 'i7_policy_version', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_i7_policy_version_status'), table_name='i7_policy_version')
    op.drop_index(op.f('ix_i7_policy_version_policy_id'), table_name='i7_policy_version')
    op.drop_table('i7_policy_version')
    # ### end Alembic commands ###
