"""ingestion_run

Revision ID: 770e63ee2f68
Revises: 
Create Date: 2026-09-10 16:43:52.603381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770e63ee2f68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('target_table', sa.String(length=128), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_run'))
    )
    op.create_index(op.f('ix_ingestion_run_source_file'), 'ingestion_run', ['source_file'], unique=False)
    op.create_index(op.f('ix_ingestion_run_target_table'), 'ingestion_run', ['target_table'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_run_target_table'), table_name='ingestion_run')
    op.drop_index(op.f('ix_ingestion_run_source_file'), table_name='ingestion_run')
    op.drop_table('ingestion_run')
    # ### end Alembic commands ###
