"""recommendation_id non-unique

Revision ID: 9392a322f0a5
Revises: c131aa566b34
Create Date: 2026-09-12 10:18:25.582113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9392a322f0a5'
down_revision: Union[str, Sequence[str], None] = 'c131aa566b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_i7_recommendation_recommendation_id'), table_name='i7_recommendation')
    op.create_index(op.f('ix_i7_recommendation_recommendation_id'), 'i7_recommendation', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_i7_recommendation_recommendation_id'), table_name='i7_recommendation')
    op.create_index(op.f('ix_i7_recommendation_recommendation_id'), 'i7_recommendation', ['recommendation_id'], unique=True)
    # ### end Alembic commands ###
