"""add i7 quarterly report table

Revision ID: b1c7daec9aca
Revises: 8b4f1e6a2d93
Create Date: 2026-09-21 16:48:10.604541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c7daec9aca'
down_revision: Union[str, Sequence[str], None] = '8b4f1e6a2d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i7_quarterly_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quarter', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('report_version', sa.String(length=16), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('feature_run_id', sa.Integer(), nullable=True),
    sa.Column('forecast_run_id', sa.Integer(), nullable=True),
    sa.Column('inventory_run_id', sa.Integer(), nullable=True),
    sa.Column('oar_run_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_quarterly_report')),
    sa.UniqueConstraint('quarter', name='uq_i7_quarterly_report_quarter')
    )
    op.create_index(op.f('ix_i7_quarterly_report_quarter'), 'i7_quarterly_report', ['quarter'], unique=False)
    op.create_index(op.f('ix_i7_quarterly_report_status'), 'i7_quarterly_report', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_i7_quarterly_report_status'), table_name='i7_quarterly_report')
    op.drop_index(op.f('ix_i7_quarterly_report_quarter'), table_name='i7_quarterly_report')
    op.drop_table('i7_quarterly_report')
    # ### end Alembic commands ###
