"""i7 oar similarity

Revision ID: b2184288fb3a
Revises: 14dfbb4d28ec
Create Date: 2026-09-12 09:45:43.306327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2184288fb3a'
down_revision: Union[str, Sequence[str], None] = '14dfbb4d28ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i7_oar_neighbour',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oar_run_id', sa.Integer(), nullable=False),
    sa.Column('sap_material_number', sa.String(length=40), nullable=False),
    sa.Column('sap_plant_code', sa.String(length=8), nullable=False),
    sa.Column('neighbour_material', sa.String(length=40), nullable=False),
    sa.Column('neighbour_plant', sa.String(length=8), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('combined_similarity', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('structured_similarity', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('text_similarity', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('business_similarity', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('score_completeness', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('same_circuit', sa.Boolean(), nullable=True),
    sa.Column('same_material_group', sa.Boolean(), nullable=True),
    sa.Column('criticality', sa.String(length=16), nullable=True),
    sa.Column('history_months', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('safety_stock', sa.Integer(), nullable=True),
    sa.Column('rop', sa.Integer(), nullable=True),
    sa.Column('max_stock', sa.Integer(), nullable=True),
    sa.Column('inventory_eligible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_oar_neighbour')),
    sa.UniqueConstraint('oar_run_id', 'sap_material_number', 'sap_plant_code', 'neighbour_material', 'neighbour_plant', name='uq_i7_oar_neighbour_key')
    )
    op.create_index(op.f('ix_i7_oar_neighbour_oar_run_id'), 'i7_oar_neighbour', ['oar_run_id'], unique=False)
    op.create_index('ix_i7_oar_neighbour_target', 'i7_oar_neighbour', ['oar_run_id', 'sap_material_number', 'sap_plant_code', 'rank'], unique=False)
    op.create_table('i7_oar_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('feature_run_id', sa.Integer(), nullable=True),
    sa.Column('inventory_run_id', sa.Integer(), nullable=True),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('embedding_model_version', sa.String(length=64), nullable=False),
    sa.Column('structured_weight', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('text_weight', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('business_weight', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('minimum_history_months', sa.Integer(), nullable=False),
    sa.Column('targets_evaluated', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_oar_run')),
    sa.UniqueConstraint('feature_run_id', 'inventory_run_id', 'policy_id', 'policy_version', 'algorithm_version', 'embedding_model_version', name='uq_i7_oar_run_inputs')
    )
    op.create_index(op.f('ix_i7_oar_run_status'), 'i7_oar_run', ['status'], unique=False)
    op.create_table('i7_oar_target',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oar_run_id', sa.Integer(), nullable=False),
    sa.Column('sap_material_number', sa.String(length=40), nullable=False),
    sa.Column('sap_plant_code', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('candidates_considered', sa.Integer(), nullable=False),
    sa.Column('eligible_candidates', sa.Integer(), nullable=False),
    sa.Column('neighbour_count', sa.Integer(), nullable=False),
    sa.Column('best_similarity', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('rejection_summary', sa.String(length=500), nullable=True),
    sa.Column('estimate_status', sa.String(length=48), nullable=False),
    sa.Column('estimate_label', sa.String(length=32), nullable=True),
    sa.Column('safety_stock', sa.Integer(), nullable=True),
    sa.Column('rop', sa.Integer(), nullable=True),
    sa.Column('max_stock', sa.Integer(), nullable=True),
    sa.Column('inventory_eligible_neighbours', sa.Integer(), nullable=False),
    sa.Column('inventory_ineligible_neighbours', sa.Integer(), nullable=False),
    sa.Column('estimate_trace', sa.String(length=1000), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_oar_target')),
    sa.UniqueConstraint('oar_run_id', 'sap_material_number', 'sap_plant_code', name='uq_i7_oar_target_key')
    )
    op.create_index(op.f('ix_i7_oar_target_estimate_status'), 'i7_oar_target', ['estimate_status'], unique=False)
    op.create_index(op.f('ix_i7_oar_target_oar_run_id'), 'i7_oar_target', ['oar_run_id'], unique=False)
    op.create_index(op.f('ix_i7_oar_target_status'), 'i7_oar_target', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_i7_oar_target_status'), table_name='i7_oar_target')
    op.drop_index(op.f('ix_i7_oar_target_oar_run_id'), table_name='i7_oar_target')
    op.drop_index(op.f('ix_i7_oar_target_estimate_status'), table_name='i7_oar_target')
    op.drop_table('i7_oar_target')
    op.drop_index(op.f('ix_i7_oar_run_status'), table_name='i7_oar_run')
    op.drop_table('i7_oar_run')
    op.drop_index('ix_i7_oar_neighbour_target', table_name='i7_oar_neighbour')
    op.drop_index(op.f('ix_i7_oar_neighbour_oar_run_id'), table_name='i7_oar_neighbour')
    op.drop_table('i7_oar_neighbour')
    # ### end Alembic commands ###
