"""i7 recommendations approval adoption

Revision ID: c131aa566b34
Revises: b2184288fb3a
Create Date: 2026-09-12 09:59:26.936144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c131aa566b34'
down_revision: Union[str, Sequence[str], None] = 'b2184288fb3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i7_approval_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.String(length=64), nullable=False),
    sa.Column('recommendation_version', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('previous_status', sa.String(length=32), nullable=False),
    sa.Column('new_status', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_approval_ledger'))
    )
    op.create_index('ix_i7_approval_ledger_action', 'i7_approval_ledger', ['action'], unique=False)
    op.create_index('ix_i7_approval_ledger_actor', 'i7_approval_ledger', ['actor_id'], unique=False)
    op.create_index('ix_i7_approval_ledger_rec', 'i7_approval_ledger', ['recommendation_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_i7_approval_ledger_recommendation_id'), 'i7_approval_ledger', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_i7_approval_ledger_timestamp'), 'i7_approval_ledger', ['timestamp'], unique=False)
    op.create_table('i7_recommendation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.String(length=64), nullable=False),
    sa.Column('sap_material_number', sa.String(length=40), nullable=False),
    sa.Column('sap_plant_code', sa.String(length=8), nullable=False),
    sa.Column('feature_run_id', sa.Integer(), nullable=True),
    sa.Column('forecast_run_id', sa.Integer(), nullable=True),
    sa.Column('inventory_run_id', sa.Integer(), nullable=True),
    sa.Column('oar_run_id', sa.Integer(), nullable=True),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('formula_version', sa.String(length=64), nullable=False),
    sa.Column('is_oar', sa.Boolean(), nullable=True),
    sa.Column('demand_class', sa.String(length=32), nullable=True),
    sa.Column('history_status', sa.String(length=32), nullable=True),
    sa.Column('criticality', sa.String(length=16), nullable=True),
    sa.Column('current_safety_stock', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('current_rop', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('current_max_stock', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('recommended_safety_stock', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('recommended_rop', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('recommended_max_stock', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('baseline_model', sa.String(length=32), nullable=True),
    sa.Column('forecast_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('lead_time_method', sa.String(length=32), nullable=True),
    sa.Column('safety_stock_method', sa.String(length=32), nullable=True),
    sa.Column('max_stock_strategy', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('oar_neighbour_count', sa.Integer(), nullable=True),
    sa.Column('oar_best_similarity', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('conversion_eligibility', sa.String(length=16), nullable=True),
    sa.Column('conversion_trigger', sa.String(length=32), nullable=True),
    sa.Column('conversion_detail', sa.String(length=500), nullable=True),
    sa.Column('blocking_reason', sa.String(length=500), nullable=True),
    sa.Column('factors_text', sa.Text(), nullable=True),
    sa.Column('calculation_trace', sa.Text(), nullable=True),
    sa.Column('impact_status', sa.String(length=48), nullable=False),
    sa.Column('safety_stock_delta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('rop_delta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('max_stock_delta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('chain_index', sa.Integer(), nullable=False),
    sa.Column('adjustment_count', sa.Integer(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_recommendation')),
    sa.UniqueConstraint('sap_material_number', 'sap_plant_code', 'feature_run_id', 'forecast_run_id', 'inventory_run_id', 'oar_run_id', 'policy_id', 'policy_version', 'formula_version', name='uq_i7_recommendation_inputs')
    )
    op.create_index('ix_i7_recommendation_material_plant', 'i7_recommendation', ['sap_material_number', 'sap_plant_code'], unique=False)
    op.create_index(op.f('ix_i7_recommendation_recommendation_id'), 'i7_recommendation', ['recommendation_id'], unique=True)
    op.create_index('ix_i7_recommendation_status', 'i7_recommendation', ['status'], unique=False)
    op.create_table('i7_recommendation_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('recommended_safety_stock', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('recommended_rop', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('recommended_max_stock', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('changed_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_recommendation_version')),
    sa.UniqueConstraint('recommendation_id', 'version', name='uq_i7_recommendation_version_key')
    )
    op.create_index('ix_i7_recommendation_version_rec', 'i7_recommendation_version', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_i7_recommendation_version_recommendation_id'), 'i7_recommendation_version', ['recommendation_id'], unique=False)
    op.create_table('i7_sap_adoption',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expected_fields', sa.String(length=500), nullable=True),
    sa.Column('observed_fields', sa.String(length=500), nullable=True),
    sa.Column('matched_fields', sa.String(length=255), nullable=True),
    sa.Column('mismatched_fields', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_sap_adoption'))
    )
    op.create_index('ix_i7_sap_adoption_rec', 'i7_sap_adoption', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_i7_sap_adoption_recommendation_id'), 'i7_sap_adoption', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_i7_sap_adoption_status'), 'i7_sap_adoption', ['status'], unique=False)
    op.create_table('i7_sap_execution_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.String(length=64), nullable=False),
    sa.Column('approved_safety_stock', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('approved_rop', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('approved_max_stock', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('executed_by', sa.String(length=64), nullable=True),
    sa.Column('execution_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sap_reference', sa.String(length=64), nullable=True),
    sa.Column('execution_status', sa.String(length=16), nullable=False),
    sa.Column('evidence_comment', sa.String(length=1000), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_sap_execution_evidence'))
    )
    op.create_index(op.f('ix_i7_sap_execution_evidence_execution_status'), 'i7_sap_execution_evidence', ['execution_status'], unique=False)
    op.create_index('ix_i7_sap_execution_evidence_rec', 'i7_sap_execution_evidence', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_i7_sap_execution_evidence_recommendation_id'), 'i7_sap_execution_evidence', ['recommendation_id'], unique=False)
    op.drop_index(op.f('ix_i7_oar_target_status'), table_name='i7_oar_target')
    op.create_index('ix_i7_oar_target_status', 'i7_oar_target', ['status', 'confidence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_i7_oar_target_status', table_name='i7_oar_target')
    op.create_index(op.f('ix_i7_oar_target_status'), 'i7_oar_target', ['status'], unique=False)
    op.drop_index(op.f('ix_i7_sap_execution_evidence_recommendation_id'), table_name='i7_sap_execution_evidence')
    op.drop_index('ix_i7_sap_execution_evidence_rec', table_name='i7_sap_execution_evidence')
    op.drop_index(op.f('ix_i7_sap_execution_evidence_execution_status'), table_name='i7_sap_execution_evidence')
    op.drop_table('i7_sap_execution_evidence')
    op.drop_index(op.f('ix_i7_sap_adoption_status'), table_name='i7_sap_adoption')
    op.drop_index(op.f('ix_i7_sap_adoption_recommendation_id'), table_name='i7_sap_adoption')
    op.drop_index('ix_i7_sap_adoption_rec', table_name='i7_sap_adoption')
    op.drop_table('i7_sap_adoption')
    op.drop_index(op.f('ix_i7_recommendation_version_recommendation_id'), table_name='i7_recommendation_version')
    op.drop_index('ix_i7_recommendation_version_rec', table_name='i7_recommendation_version')
    op.drop_table('i7_recommendation_version')
    op.drop_index('ix_i7_recommendation_status', table_name='i7_recommendation')
    op.drop_index(op.f('ix_i7_recommendation_recommendation_id'), table_name='i7_recommendation')
    op.drop_index('ix_i7_recommendation_material_plant', table_name='i7_recommendation')
    op.drop_table('i7_recommendation')
    op.drop_index(op.f('ix_i7_approval_ledger_timestamp'), table_name='i7_approval_ledger')
    op.drop_index(op.f('ix_i7_approval_ledger_recommendation_id'), table_name='i7_approval_ledger')
    op.drop_index('ix_i7_approval_ledger_rec', table_name='i7_approval_ledger')
    op.drop_index('ix_i7_approval_ledger_actor', table_name='i7_approval_ledger')
    op.drop_index('ix_i7_approval_ledger_action', table_name='i7_approval_ledger')
    op.drop_table('i7_approval_ledger')
    # ### end Alembic commands ###
