"""i7 feature store

Revision ID: dade804dfca6
Revises: e81cb7fed15a
Create Date: 2026-09-11 14:16:00.986273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dade804dfca6'
down_revision: Union[str, Sequence[str], None] = 'e81cb7fed15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i7_feature_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('features_built', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('consumption_movement_types', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_feature_run'))
    )
    op.create_index(op.f('ix_i7_feature_run_status'), 'i7_feature_run', ['status'], unique=False)
    op.create_table('i7_material_feature',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sap_material_number', sa.String(length=40), nullable=False),
    sa.Column('sap_plant_code', sa.String(length=8), nullable=False),
    sa.Column('total_periods', sa.Integer(), nullable=False),
    sa.Column('non_zero_periods', sa.Integer(), nullable=False),
    sa.Column('first_period', sa.Date(), nullable=True),
    sa.Column('last_period', sa.Date(), nullable=True),
    sa.Column('history_months', sa.Integer(), nullable=False),
    sa.Column('history_status', sa.String(length=32), nullable=False),
    sa.Column('data_sufficiency', sa.String(length=32), nullable=False),
    sa.Column('required_history_months', sa.Integer(), nullable=True),
    sa.Column('total_demand', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('mean_demand_all_periods', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('std_dev_demand_all_periods', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('mean_non_zero_demand', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('std_dev_non_zero_demand', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('adi', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('adi_status', sa.String(length=32), nullable=False),
    sa.Column('cv_squared', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('cv_squared_status', sa.String(length=32), nullable=False),
    sa.Column('demand_class', sa.String(length=32), nullable=False),
    sa.Column('baseline_model', sa.String(length=32), nullable=True),
    sa.Column('challenger_model', sa.String(length=32), nullable=True),
    sa.Column('routing_reason', sa.String(length=255), nullable=True),
    sa.Column('oar_scope', sa.String(length=32), nullable=False),
    sa.Column('oar_reason', sa.String(length=255), nullable=True),
    sa.Column('oar_rollup_status', sa.String(length=32), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=True),
    sa.Column('mrp_type', sa.String(length=8), nullable=True),
    sa.Column('material_status', sa.String(length=8), nullable=True),
    sa.Column('has_criticality', sa.Boolean(), nullable=False),
    sa.Column('has_mrp_type', sa.Boolean(), nullable=False),
    sa.Column('has_material_status', sa.Boolean(), nullable=False),
    sa.Column('has_consumption', sa.Boolean(), nullable=False),
    sa.Column('has_lead_time', sa.Boolean(), nullable=False),
    sa.Column('purchase_order_count', sa.Integer(), nullable=False),
    sa.Column('feature_run_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_material_feature')),
    sa.UniqueConstraint('sap_material_number', 'sap_plant_code', name='uq_i7_material_feature_key')
    )
    op.create_index('ix_i7_material_feature_class', 'i7_material_feature', ['demand_class', 'sap_plant_code'], unique=False)
    op.create_index(op.f('ix_i7_material_feature_feature_run_id'), 'i7_material_feature', ['feature_run_id'], unique=False)
    op.create_index(op.f('ix_i7_material_feature_history_status'), 'i7_material_feature', ['history_status'], unique=False)
    op.create_index('ix_i7_material_feature_oar', 'i7_material_feature', ['oar_scope', 'sap_plant_code'], unique=False)
    op.create_index(op.f('ix_i7_material_feature_oar_scope'), 'i7_material_feature', ['oar_scope'], unique=False)
    op.create_index(op.f('ix_i7_material_feature_sap_material_number'), 'i7_material_feature', ['sap_material_number'], unique=False)
    op.create_index(op.f('ix_i7_material_feature_sap_plant_code'), 'i7_material_feature', ['sap_plant_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_i7_material_feature_sap_plant_code'), table_name='i7_material_feature')
    op.drop_index(op.f('ix_i7_material_feature_sap_material_number'), table_name='i7_material_feature')
    op.drop_index(op.f('ix_i7_material_feature_oar_scope'), table_name='i7_material_feature')
    op.drop_index('ix_i7_material_feature_oar', table_name='i7_material_feature')
    op.drop_index(op.f('ix_i7_material_feature_history_status'), table_name='i7_material_feature')
    op.drop_index(op.f('ix_i7_material_feature_feature_run_id'), table_name='i7_material_feature')
    op.drop_index('ix_i7_material_feature_class', table_name='i7_material_feature')
    op.drop_table('i7_material_feature')
    op.drop_index(op.f('ix_i7_feature_run_status'), table_name='i7_feature_run')
    op.drop_table('i7_feature_run')
    # ### end Alembic commands ###
