"""i7 staging tables

Revision ID: e81cb7fed15a
Revises: 6ed5f8189d4a
Create Date: 2026-09-11 12:56:16.763007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81cb7fed15a'
down_revision: Union[str, Sequence[str], None] = '6ed5f8189d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i7_staged_consumption',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sap_material_number', sa.String(length=40), nullable=False),
    sa.Column('sap_plant_code', sa.String(length=8), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=8), nullable=True),
    sa.Column('movement_count', sa.Integer(), nullable=False),
    sa.Column('source_table', sa.String(length=64), nullable=False),
    sa.Column('staging_run_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_staged_consumption')),
    sa.UniqueConstraint('sap_material_number', 'sap_plant_code', 'period', name='uq_i7_staged_consumption_key')
    )
    op.create_index('ix_i7_staged_consumption_series', 'i7_staged_consumption', ['sap_material_number', 'sap_plant_code', 'period'], unique=False)
    op.create_index(op.f('ix_i7_staged_consumption_staging_run_id'), 'i7_staged_consumption', ['staging_run_id'], unique=False)
    op.create_table('i7_staged_material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sap_material_number', sa.String(length=40), nullable=False),
    sa.Column('app_material_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('material_group', sa.String(length=32), nullable=True),
    sa.Column('base_unit_of_measure', sa.String(length=8), nullable=True),
    sa.Column('material_status', sa.String(length=8), nullable=True),
    sa.Column('external_material_group', sa.String(length=32), nullable=True),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('deletion_flag', sa.Boolean(), nullable=True),
    sa.Column('criticality', sa.String(length=16), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('source_table', sa.String(length=64), nullable=False),
    sa.Column('staging_run_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_staged_material')),
    sa.UniqueConstraint('sap_material_number', name='uq_i7_staged_material_sap_material_number')
    )
    op.create_index(op.f('ix_i7_staged_material_criticality'), 'i7_staged_material', ['criticality'], unique=False)
    op.create_index(op.f('ix_i7_staged_material_material_group'), 'i7_staged_material', ['material_group'], unique=False)
    op.create_index(op.f('ix_i7_staged_material_material_status'), 'i7_staged_material', ['material_status'], unique=False)
    op.create_index(op.f('ix_i7_staged_material_sap_material_number'), 'i7_staged_material', ['sap_material_number'], unique=False)
    op.create_index(op.f('ix_i7_staged_material_staging_run_id'), 'i7_staged_material', ['staging_run_id'], unique=False)
    op.create_table('i7_staged_material_plant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sap_material_number', sa.String(length=40), nullable=False),
    sa.Column('sap_plant_code', sa.String(length=8), nullable=False),
    sa.Column('app_plant_id', sa.String(length=64), nullable=True),
    sa.Column('mrp_type', sa.String(length=8), nullable=True),
    sa.Column('planned_delivery_time_days', sa.Integer(), nullable=True),
    sa.Column('current_safety_stock', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('current_reorder_point', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('current_maximum_stock', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('deletion_flag', sa.Boolean(), nullable=True),
    sa.Column('source_table', sa.String(length=64), nullable=False),
    sa.Column('staging_run_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_staged_material_plant')),
    sa.UniqueConstraint('sap_material_number', 'sap_plant_code', name='uq_i7_staged_material_plant_key')
    )
    op.create_index(op.f('ix_i7_staged_material_plant_mrp_type'), 'i7_staged_material_plant', ['mrp_type'], unique=False)
    op.create_index(op.f('ix_i7_staged_material_plant_sap_material_number'), 'i7_staged_material_plant', ['sap_material_number'], unique=False)
    op.create_index(op.f('ix_i7_staged_material_plant_sap_plant_code'), 'i7_staged_material_plant', ['sap_plant_code'], unique=False)
    op.create_index(op.f('ix_i7_staged_material_plant_staging_run_id'), 'i7_staged_material_plant', ['staging_run_id'], unique=False)
    op.create_table('i7_staged_purchase_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchasing_document', sa.String(length=20), nullable=False),
    sa.Column('item', sa.String(length=10), nullable=False),
    sa.Column('sap_material_number', sa.String(length=40), nullable=False),
    sa.Column('sap_plant_code', sa.String(length=8), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('goods_receipt_date', sa.Date(), nullable=True),
    sa.Column('planned_delivery_date', sa.Date(), nullable=True),
    sa.Column('planned_delivery_time_days', sa.Integer(), nullable=True),
    sa.Column('quantity_ordered', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('quantity_received', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('supplier', sa.String(length=20), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('source_table', sa.String(length=64), nullable=False),
    sa.Column('staging_run_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_staged_purchase_order')),
    sa.UniqueConstraint('purchasing_document', 'item', name='uq_i7_staged_purchase_order_key')
    )
    op.create_index('ix_i7_staged_purchase_order_material_plant', 'i7_staged_purchase_order', ['sap_material_number', 'sap_plant_code'], unique=False)
    op.create_index(op.f('ix_i7_staged_purchase_order_sap_material_number'), 'i7_staged_purchase_order', ['sap_material_number'], unique=False)
    op.create_index(op.f('ix_i7_staged_purchase_order_staging_run_id'), 'i7_staged_purchase_order', ['staging_run_id'], unique=False)
    op.create_table('i7_staging_rejection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staging_run_id', sa.Integer(), nullable=False),
    sa.Column('source_table', sa.String(length=64), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_staging_rejection'))
    )
    op.create_index(op.f('ix_i7_staging_rejection_reason'), 'i7_staging_rejection', ['reason'], unique=False)
    op.create_index('ix_i7_staging_rejection_run_reason', 'i7_staging_rejection', ['staging_run_id', 'reason'], unique=False)
    op.create_index(op.f('ix_i7_staging_rejection_source_table'), 'i7_staging_rejection', ['source_table'], unique=False)
    op.create_index(op.f('ix_i7_staging_rejection_staging_run_id'), 'i7_staging_rejection', ['staging_run_id'], unique=False)
    op.create_table('i7_staging_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('materials_staged', sa.Integer(), nullable=False),
    sa.Column('material_plants_staged', sa.Integer(), nullable=False),
    sa.Column('consumption_staged', sa.Integer(), nullable=False),
    sa.Column('purchase_orders_staged', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('consumption_movement_types', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_staging_run'))
    )
    op.create_index(op.f('ix_i7_staging_run_source'), 'i7_staging_run', ['source'], unique=False)
    op.create_index(op.f('ix_i7_staging_run_status'), 'i7_staging_run', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_i7_staging_run_status'), table_name='i7_staging_run')
    op.drop_index(op.f('ix_i7_staging_run_source'), table_name='i7_staging_run')
    op.drop_table('i7_staging_run')
    op.drop_index(op.f('ix_i7_staging_rejection_staging_run_id'), table_name='i7_staging_rejection')
    op.drop_index(op.f('ix_i7_staging_rejection_source_table'), table_name='i7_staging_rejection')
    op.drop_index('ix_i7_staging_rejection_run_reason', table_name='i7_staging_rejection')
    op.drop_index(op.f('ix_i7_staging_rejection_reason'), table_name='i7_staging_rejection')
    op.drop_table('i7_staging_rejection')
    op.drop_index(op.f('ix_i7_staged_purchase_order_staging_run_id'), table_name='i7_staged_purchase_order')
    op.drop_index(op.f('ix_i7_staged_purchase_order_sap_material_number'), table_name='i7_staged_purchase_order')
    op.drop_index('ix_i7_staged_purchase_order_material_plant', table_name='i7_staged_purchase_order')
    op.drop_table('i7_staged_purchase_order')
    op.drop_index(op.f('ix_i7_staged_material_plant_staging_run_id'), table_name='i7_staged_material_plant')
    op.drop_index(op.f('ix_i7_staged_material_plant_sap_plant_code'), table_name='i7_staged_material_plant')
    op.drop_index(op.f('ix_i7_staged_material_plant_sap_material_number'), table_name='i7_staged_material_plant')
    op.drop_index(op.f('ix_i7_staged_material_plant_mrp_type'), table_name='i7_staged_material_plant')
    op.drop_table('i7_staged_material_plant')
    op.drop_index(op.f('ix_i7_staged_material_staging_run_id'), table_name='i7_staged_material')
    op.drop_index(op.f('ix_i7_staged_material_sap_material_number'), table_name='i7_staged_material')
    op.drop_index(op.f('ix_i7_staged_material_material_status'), table_name='i7_staged_material')
    op.drop_index(op.f('ix_i7_staged_material_material_group'), table_name='i7_staged_material')
    op.drop_index(op.f('ix_i7_staged_material_criticality'), table_name='i7_staged_material')
    op.drop_table('i7_staged_material')
    op.drop_index(op.f('ix_i7_staged_consumption_staging_run_id'), table_name='i7_staged_consumption')
    op.drop_index('ix_i7_staged_consumption_series', table_name='i7_staged_consumption')
    op.drop_table('i7_staged_consumption')
    # ### end Alembic commands ###
