"""add MARD stock staging and stock-position features

Revision ID: f7684f17af15
Revises: fb740ec1d985
Create Date: 2026-09-16 11:30:01.407371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7684f17af15'
down_revision: Union[str, Sequence[str], None] = 'fb740ec1d985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i7_staged_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sap_material_number', sa.String(length=40), nullable=False),
    sa.Column('sap_plant_code', sa.String(length=8), nullable=False),
    sa.Column('storage_location', sa.String(length=8), nullable=False),
    sa.Column('unrestricted_use_stock', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('quality_inspection_stock', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('blocked_stock', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('stock_in_transfer', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('restricted_use_stock', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('returns_stock', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('source_table', sa.String(length=64), nullable=False),
    sa.Column('staging_run_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i7_staged_stock')),
    sa.UniqueConstraint('sap_material_number', 'sap_plant_code', 'storage_location', name='uq_i7_staged_stock_key')
    )
    op.create_index('ix_i7_staged_stock_material_plant', 'i7_staged_stock', ['sap_material_number', 'sap_plant_code'], unique=False)
    op.create_index(op.f('ix_i7_staged_stock_staging_run_id'), 'i7_staged_stock', ['staging_run_id'], unique=False)
    op.add_column('i7_material_feature', sa.Column('current_stock', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('i7_material_feature', sa.Column('quality_inspection_stock', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('i7_material_feature', sa.Column('blocked_stock', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('i7_material_feature', sa.Column('stock_in_transfer', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('i7_material_feature', sa.Column('restricted_use_stock', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('i7_material_feature', sa.Column('returns_stock', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column(
        'i7_material_feature',
        sa.Column('has_stock_data', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'i7_material_feature',
        sa.Column('storage_location_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'i7_staging_run',
        sa.Column('stock_staged', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('i7_staging_run', 'stock_staged')
    op.drop_column('i7_material_feature', 'storage_location_count')
    op.drop_column('i7_material_feature', 'has_stock_data')
    op.drop_column('i7_material_feature', 'returns_stock')
    op.drop_column('i7_material_feature', 'restricted_use_stock')
    op.drop_column('i7_material_feature', 'stock_in_transfer')
    op.drop_column('i7_material_feature', 'blocked_stock')
    op.drop_column('i7_material_feature', 'quality_inspection_stock')
    op.drop_column('i7_material_feature', 'current_stock')
    op.drop_index(op.f('ix_i7_staged_stock_staging_run_id'), table_name='i7_staged_stock')
    op.drop_index('ix_i7_staged_stock_material_plant', table_name='i7_staged_stock')
    op.drop_table('i7_staged_stock')
    # ### end Alembic commands ###
