"""add MRP parameters and lead-time source to i7_material_feature

Revision ID: fb740ec1d985
Revises: 64f7682e1dc1
Create Date: 2026-09-15 18:48:53.679360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb740ec1d985'
down_revision: Union[str, Sequence[str], None] = '64f7682e1dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('i7_material_feature', sa.Column('current_safety_stock', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('i7_material_feature', sa.Column('current_reorder_point', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('i7_material_feature', sa.Column('current_maximum_stock', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('i7_material_feature', sa.Column('planned_delivery_time_days', sa.Integer(), nullable=True))
    op.add_column('i7_material_feature', sa.Column('lead_time_source', sa.String(length=32), nullable=True))
    op.add_column('i7_material_feature', sa.Column('lead_time_days', sa.Numeric(precision=18, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('i7_material_feature', 'lead_time_days')
    op.drop_column('i7_material_feature', 'lead_time_source')
    op.drop_column('i7_material_feature', 'planned_delivery_time_days')
    op.drop_column('i7_material_feature', 'current_maximum_stock')
    op.drop_column('i7_material_feature', 'current_reorder_point')
    op.drop_column('i7_material_feature', 'current_safety_stock')
    # ### end Alembic commands ###
